### ISSUE TITLE
Warning after file upload

### ISSUE THREAD

**Issue by followflydge** [pqina/react-filepond#18]
HI, i found a problem

> TypeError: Cannot read property 'filename' of null
    at Object.itemProcessed [as DID_COMPLETE_ITEM_PROCESSING] (filepond.js:6829)

This happens after file is uploaded, and all works fine, except for this warning
I upload files using proccessHandler and it just take arguments from the filepond and uses it for my logic

```javascript
 <FilePond
                        allowMultiple={ allowMultiply }
                        allowReplace={ !allowMultiply }
                        allowDrop={ allowDrop }
                        allowBrowse={ allowBrowse }
                        maxFiles={ maxFiles }
                        server={ this.serverOptions }
                        maxFileSize={ maxFileSize }
                        maxTotalFileSize={ maxTotalFileSize }
                        acceptedFileTypes={ acceptedFileTypes }
                        instantUpload={ instantUpload }
                        allowRevert={ allowRevert }
                        allowFileSizeValidation={ allowFileSizeValidation }
                        allowFileTypeValidation={ allowFileTypeValidation }
                        { ...this.translatedText() }
                        files={ !this.hasFileUploaded() ? [] : [
                            {
                                options: {
                                    type: 'limbo',
                                    file: {
                                        name: this.getFileName(),
                                        size: this.getFileSize(),
                                    },
                                },
                            },
                        ] }
                    >
                    </FilePond>
```

```javascript
   serverOptions = {
        process: this.processHandler,
        revert: this.revertHandler,
    };
```

```javascript
    processHandler = ( fieldName, file, metadata, load, error ) => {
        const { formType } = this.props;
        const sendingBody = `
            {
                "requestId": "${uuidv4()}",
                "operation": "PROCESS",
                "file": {
                    "name": "${file.name}",
                    "content": "${metadata.base64}"
                }
            }
            `;

        fileSocketSend( formType, load, error, sendingBody,
            this.handlerForProcessHandlerSocket);
    };
```

| Environment  | Version
|------------- | -----------
| OS        | Windows
| Browser   |  Latest Chrome

**Comment by raRaRa** [comment]
I'm getting the same error.

```
  var itemProcessed = function itemProcessed(_ref4) {
    var root = _ref4.root,
        action = _ref4.action; // will also notify the user when FilePond is not being used, as the user might be occupied with other activities while uploading a file

    var item = root.query('GET_ITEM', action.id);
    var filename = item.filename;
    var label = root.query('GET_LABEL_FILE_PROCESSING_COMPLETE');
    assist(root, filename + ' ' + label);
  };
```

The error occurs on:
> var filename = item.filename;

So for some reason item is null for item processed.

**Comment by raRaRa** [comment]
It seems to happen if the component is re-rendered after file upload. My guess is that this could be some kind of conflict when the last File disappeared during the re-rendering phase, and new one was added. At least it kinda makes sense, since FileUploader will lose ref to the last File.

**Comment by raRaRa** [comment]
The problem goes away if I skip the last step in my custom processor, which is `load(file)`

My new theory is that the `load(file)` is somehow conflicting with the <File> component which gets updated.

**Comment by rikschennink** [comment]
@raRaRa is `file` a string? or unique file identifier? It should not be a file object.

@followflydge same question, what kind of parameter is passed to the load method from within `fileSocketSend`?

**Comment by raRaRa** [comment]
@rikschennink Ah ok, I changed it to the filename, but I still have the same issue. I also noticed that after calling `load('unique-filename')`, it seems to call `onremovefile` for the same file, causing the uploaded file to be removed immediately (if you have onremovefile handler).

My code is fairly simple. I use Redux to store the URL path to the single file, which updates the prop currentFile in my component. This causes the `<File>` to be added. It should be fairly easy to re-produce.

In my case there's already an uploaded file, I click on X to remove it, upload a new file, it uploads and immediately onremovefile is called for the new file.

```
            <FilePond
                ref={this.filePondRef}
                maxFiles={1}
                labelIdle="Drag and drop media or <span class='filepond--label-action'> Browse </span>"
                maxFileSize="60MB"
                acceptedFileTypes={['image/*', 'video/mp4', 'video/webm']}
                server={this.server}
                onremovefile={this.onRemoveFile}
            >
                {this.props.currentFile && (
                    <File key={this.props.currentFile} src={this.props.currentFile} origin="local" />
                )}
            </FilePond>
```


I worked around this issue by modifying your react-filepond lib. Instead of using <File> I now pass a currentFile prop to <FilePond>, which creates FilePond with the file in the FilePond constructor. That way everything seems to work just fine. But in theory this should work exactly the same, I'll see if I can find the culprit.

**Comment by raRaRa** [comment]
I've been trying to figure out what's going on. It's definitely related to calling `this._pond.setOptions(options)` inside react-filepond.

The FilePond was initialized with empty files, or `[]`.

I upload a file and observe that setOptions is called correctly AFAIK. One file with the correct properties and previousFiles was empty, `[]`
<img src="https://i.imgur.com/sP1FeXV.png"/>

This looks fine. But immediately after calling `setOptions`, the `onremovefile` callback is fired. Something is triggering the same file to be deleted immediately, causing the ref issues I believe.

So unfortunately this seems to be an internal bug with filepond.js with `setOptions`.

I could go further, such as experimenting with addFile, removeFile in `componentDidUpdate`, depending on what changed, but I'm going to see what @rikschennink has to say.

Hope this helps fixing the problem.

**Comment by followflydge** [comment]
@rikschennink Thanks for the good question, I just call the load() method without arguments. when I deleted load() - the warning disappeared

**Comment by rikschennink** [comment]
@raRaRa Thanks so much for the detailed investigation. I'm currently at a conference but will definitely pick this up at the start of next week.

**Comment by raRaRa** [comment]
And here's my final investigation, deleting the one above since it could be misleading.

I noticed that when calling `load()` without adding the file as a `<File>` component, it works fine with no error.

However, if I add the `<File>` component after calling `load()`, it crashes on this error. This means that `setOptions` is called after `load()` and it triggers `onremovefile`

If I do this the opposite way, add the `<File>` before calling `load()`, then it will immediately crash with the same error, so it's like `setOptions` is causing onremovefile to be triggered. And the `load()` call will also cause this error, so I get two errors in total.

If I don't call `load()` at all, but add the `<File>` component, it will trigger `onremovefile()` as well. 

So in all cases, `setOptions` is triggering `onremovefile` to be called. Even if `previousFiles` is empty and `currentFiles` has the new file. It'll trigger `onremovefile` on the new file.

**Comment by raRaRa** [comment]
So I went a bit further with this. I noticed that `load()` will actually add the file. So during `componentDidUpdate` in react-filepond, it's diffing previousFiles with currentFiles, where previousFiles is an empty array and currentFiles has the new file. Which is kinda wrong, because if you call this._pond.getFiles() it will return the new file (which was added with `load()`).

Based on this, react-filepond is calling `setOptions` with the new file, even though the new file has already been added, which I believe causes the already added file to be removed, which will cause the crash, because it'll be removing the file it's adding.

One potential "hack" to fix this is to make sure that _pond.getFiles() AND previousFiles do not match currentFiles. So if one of them matches, do nothing.

The ideal fix would be to make sure that setOptions isn't removing the already added file, but I'm not familiar with filepond.eml.js to look into it myself.

**Comment by raRaRa** [comment]
Hey @rikschennink 

Here you go.

Source code:
https://codesandbox.io/s/6y1py4x9nr

Preview:
 https://6y1py4x9nr.codesandbox.io/

**Comment by raRaRa** [comment]
Just let me know if there's anything more I can do to help out. Really lovin' FilePond!

**Comment by rikschennink** [comment]
This is a collision between external state and the FilePond internal state (as internally it's a vanilla JavaScript library). :\ Tricky situation. Normally the `files` property (which the `<File/>` children are bound to) is only set on page load. After that, FilePond takes over.

In the situation above the files property receives an update after it has been updated internally already.

I managed to make it work like this, use the file source instead of the file name so internally the values are compared correctly (note that the onaddfile and onremove file callbacks don't do anything, they're just for logging):

```jsx
<FilePond
    server='http://192.168.33.11'
    ref={ref => this.pond = ref}
    onprocessfile={(err, fileItem) => {

        console.log('onprocessfile', fileItem.filename, fileItem.source);

        this.setState({
            currentFile: {
                source: fileItem.source,
                options: {
                    type: 'local'
                }
            }
        });

    }}
    onaddfile={(err, fileItem) => {

        console.log('onaddfile', fileItem.filename, fileItem.source);

    }}
    onremovefile={(fileItem) => {

        console.log('onremovefile', fileItem.filename);

    }}>
    {this.state.currentFile && (
        <File 
            src={this.state.currentFile.source} 
            origin={this.state.currentFile.options.type} />
    )}
</FilePond>
```

**Comment by raRaRa** [comment]
Clever trick, works for me.

One quick question. When an upload has finished, it shows a X icon that has the title `Remove` next to the `Upload complete` text. When I click on the X icon, FilePond offers me to remove it again by showing the X icon on the left side, or re-upload the image on the right side. Is it possible to remove this step? I find it a bit confusing UX-wise. I would rather like to see file with the X icon alone.

Thanks.

**Comment by rikschennink** [comment]
@raRaRa Great!

If you set `instantUpload` to `true` it will immediately remove the file.

**Comment by raRaRa** [comment]
@rikschennink Hmm, doesn't work for newly uploaded file, where you have the green background and the text "Upload complete". The remove button there takes you to another step where you can remove again, or re-upload.

**Comment by raRaRa** [comment]
@rikschennink Regarding the collision between external and internal state of FilePond. I had one idea in react-filepond.

Under `componentDidUpdate`, you could check the internal files and compare it with currentFiles, and assign the source there.

Example:

```
    // file list has changed
    if (JSON.stringify(previousFiles) !== JSON.stringify(currentFiles)) {
      const currentInternalFiles = this._pond.getFiles()
      if (currentInternalFiles && currentInternalFiles.length > 0) {
        for (let i = 0; i < currentInternalFiles.length; i++) {
          for (let x = 0; x < currentFiles.length; x++) {
            if (currentFiles[x].source === currentInternalFiles[i].source.name) {
              currentFiles[x] = currentInternalFiles[i]
            }
          }
        }
      }

      options.files = currentFiles;
    }
```

I also had to use `decodeURIComponent` for the file name, since the external has encoded file name.

Just an idea.

**Comment by rikschennink** [comment]
Yeah, I played with that as well but still the results were not perfect. 

I'm currently writing some tests to cover all kinds of `pond.files` updates, that way I can hopefully resolve the problem in the internal `files` diff and I fix the issue for both React, Vue and Angular.

**Comment by rikschennink** [comment]
I've updated the React component to version `5.0.0` and updated FilePond to `3.1.0`, please note that FilePond is now a peerDependency.

I have added the `onupdatefiles` callback which you can use to sync up the files list inside FilePond with the one in your component. I've extensively tested this, but still, there's a chance it might cause trouble in some situations, happy to help out if needed.

See docs for detailed information on changes:
https://pqina.nl/filepond/docs/patterns/frameworks/react/

**Comment by cs-manughian** [comment]
@rikschennink / @pqina I tried the solution in the documentation using onupdatefiles for React, but it was not working. I want to pass in file objects from my parent component in the FilePond and then have the FilePond manage the state from there, while updating the parent on change. I implemented your suggestion, but FilePond keeps calling onaddfile and onremovefile right after it passes in the initial files, and then the FilePond acts buggy from there trying to manage the external and internal state. Any ideas please? I've been fiddling with this for about a day now. Any help would be appreciated!

**Comment by rikschennink** [comment]
@cs-manughian Looking into it now

**Comment by cs-manughian** [comment]
@rikschennink thank you! All the help would be appreciated

**Comment by rikschennink** [comment]
@cs-manughian I've confirmed the issue, it's fixed locally, please update the react adapter to version `6.0.1` and the filepond core to `3.7.7` this should fix the issue.

Please note that the `<File>` component has been removed, you can now simply use the `files` prop to set the files.

Let me know if this resolves the problem on your side.

**Comment by cs-manughian** [comment]
@rikschennink thanks for your prompt reply! I'm going to try this out shortly and let you know. Thanks!

**Comment by cs-manughian** [comment]
@rikschennink What's react adapter? I updated the filepond version to 3.7.7, I removed the File element, and I populated the files property with the files list, but it still doesn't seem to be behaving. So I have an array of file objects that I'm passing to the FilePond component from the parent properties. The file object looks like this:
```
      files: [
        {
          dateUploaded: "2019-01-17T22:10:06.658Z",
          originalFileName: "Innovation.txt",
          source: "C:\\APIUploads\\Innovation-Thu17Jan2019221006GMT.txt",
          size: 0,
          type: "text/plain",
          visibility: "public",
          options: { type: "local" }
        }
      ]

I added the options property to it. I then pass this list into the files property on FilePond, and I set the onupdatefiles function as per the documentation, but it still is not working. Please let me know what you think! Your help is appreciated.

I have these other properties set on FilePond:```

```

          ref={ref => this.pond=ref} // To call instance methods
          oninit={() => this.setPondOptions()}
          onaddfile={(err, file) => this.onAddFile(err, file)}
          onremovefile={(err, file) => this.onRemoveFile(err, file)}
          onerror={res => console.log(res)}
          labelIdle={
              labelIdle
            ? labelIdle + `<div class="sub-label">${subLabelIdle}</div>`
            : "Drag & drop, or <u>Browse</u>, file(s) to upload"
          }
          allowBrowse={isEditable}
          allowDrop={isEditable}
          allowRevert={isEditable}
          allowPaste={isEditable}
          allowMultiple={allowMultiple ? allowMultiple : false} 
          allowFileSizeValidation={true}
          allowFileTypeValidation={true}
          acceptedFileTypes={acceptedFileTypes ? acceptedFileTypes : []}
          maxFileSize={
              maxFileSize 
            ? maxFileSize 
            : process.env.REACT_APP_MAX_FILE_SIZE_BYTES
          }
          maxFiles={process.env.REACT_APP_MAX_FILES} 
          files={files}
          server={server}
```

**Comment by cs-manughian** [comment]
@rikschennink thanks for your reply. So I updated my code to use an array of URLs, and that looks like it's working, but it's submitting a GET request to my server with the param "?fetch=" or "?load=", causing a 404. I want to use an absolute URL to pre-populate the files and then use my server's current file endpoint to handle the upload. Is this possible?

**Comment by rikschennink** [comment]
The `fetch` end point is for loading dropped URLs from remote sites. The `load` end point is for loading files in filepond that have already been uploaded to your server (files that have `options.type` set to `local`). For instance to render an image preview.

It depends on what you’re trying to achieve, it’s not a 100 percent clear to me what that is.

**Comment by cs-manughian** [comment]
@rikschennink Thank you. So I want to use a remote URL for the initial fetching/pre-population and I want to use my server endpoint for the upload. Do I have to implement the route for the fetch endpoint on my server, or can filepond be configured to use just the remote URL to grab the images?

**Comment by rikschennink** [comment]
@cs-manughian Yes, that is correct, unless you have access to the remote server and can set the required CORS policies the browser cannot fetch the file. So in that situation FilePond will request/fetch the file from the server.

**Comment by dineshtalekar777** [comment]
@raRaRa  I am getting error for maxFileSize="60MB" this attribute can you please share the working file size validation example

**Comment by akshay-1707** [comment]
@dineshtalekar777  is file pond working for u properly need a small help?
